### ISSUE TITLE
Geopandas Error on Copernicus

### ISSUE THREAD

**Issue by DaveCasson** [CH-Earth/summaWorkflow_public#77]
A similar geopandas error come up on several Copernicus Workflows.
Example below: 

(summa-venv) [drc858@cniclgn01 2_forcing]$ python 1_make_one_weighted_forcing_file.py
EASYMORE is given multiple varibales to be remapped but only on format and fill valueEASYMORE repeat the format and fill value for all the variables in output files
EASYMORE will remap variable  airpres  from source file to variable  airpres  in remapped NeCDF file
EASYMORE will remap variable  LWRadAtm  from source file to variable  LWRadAtm  in remapped NeCDF file
EASYMORE will remap variable  SWRadAtm  from source file to variable  SWRadAtm  in remapped NeCDF file
EASYMORE will remap variable  pptrate  from source file to variable  pptrate  in remapped NeCDF file
EASYMORE will remap variable  airtemp  from source file to variable  airtemp  in remapped NeCDF file
EASYMORE will remap variable  spechum  from source file to variable  spechum  in remapped NeCDF file
EASYMORE will remap variable  windspd  from source file to variable  windspd  in remapped NeCDF file
Traceback (most recent call last):
  File "1_make_one_weighted_forcing_file.py", line 212, in <module>
    esmr.nc_remapper()
  File "/globalhome/drc858/HPC/summa-venv/lib/python3.8/site-packages/easymore/easymore.py", line 66, in nc_remapper
    import geopandas as gpd
  File "/globalhome/drc858/HPC/summa-venv/lib/python3.8/site-packages/geopandas/__init__.py", line 1, in <module>
    from geopandas._config import options  # noqa
  File "/globalhome/drc858/HPC/summa-venv/lib/python3.8/site-packages/geopandas/_config.py", line 126, in <module>
    default_value=_default_use_pygeos(),
  File "/globalhome/drc858/HPC/summa-venv/lib/python3.8/site-packages/geopandas/_config.py", line 112, in _default_use_pygeos
    import geopandas._compat as compat
  File "/globalhome/drc858/HPC/summa-venv/lib/python3.8/site-packages/geopandas/_compat.py", line 149, in <module>
    import rtree  # noqa
  File "/globalhome/drc858/HPC/summa-venv/lib/python3.8/site-packages/rtree/__init__.py", line 1, in <module>
    from .index import Rtree
  File "/globalhome/drc858/HPC/summa-venv/lib/python3.8/site-packages/rtree/index.py", line 6, in <module>
    from . import core
  File "/globalhome/drc858/HPC/summa-venv/lib/python3.8/site-packages/rtree/core.py", line 146, in <module>
    rt.Error_GetLastErrorNum.restype = ctypes.c_int
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python: undefined symbol: Error_GetLastErrorNum

**Comment by DaveCasson** [comment]
Adding solution provided by Wouter: 

module load python/3.7
module load scipy-stack
module load proj/7.0.1
module load geos/3.8.1
module load gdal/3.0.4
virtualenv --no-download geopandas-env
source geopandas-env/bin/activate
pip install --no-index --upgrade pip
pip install --no-index geopandas
deactivate

**Comment by wknoben** [comment]
I'll close this and add that info to the wiki
